export const userInputs = [
    {
      id: "nik",
      label: "NIK",
      type: "text",
      placeholder: "NIK 16 Digit",
    },
    {
      id: "nama",
      label: "NAMA",
      type: "text",
      placeholder: "john_doe",
    },
    {
      id: "keterangan",
      label: "Keterangan",
      type: "select",
      placeholder: "Keterangan",
      options: [
        { value: "option1", label: "PEMULA" },
        { value: "option2", label: "KEHILANGAN" },
        { value: "option3", label: "CETAK ULANG(CU)" },
        { value: "option4", label: "KADOMBAKITA" },
        { value: "option5", label: "ONLINE SKD" },
        { value: "option6", label: "ONLINE AKM" },
        { value: "option7", label: "ONLINE BIODATA" },
        { value: "option8", label: "PERUBAHAN DATA" },
        { value: "option9", label: "BANTUAN PINDAH" },
        { value: "option10", label: "GANTI FOTO" },
        { value: "option11", label: "GANTI TTD" },
        { value: "option12", label: "GANTI FOTO + TTD" },
        { value: "option13", label: "SKD + GANTI FOTO" },
        { value: "option14", label: "LD" },
        { value: "option15", label: "RUSAK" },
      ],
    },
    {
      id: "tanggal",
      label: "Tanggal",
      type: "date",
      placeholder: "dd/mm/yyyy",
    },
  ];
  
  export const dinasInputs = [
    {
      id: "nik",
      label: "NIK",
      type: "text",
      placeholder: "NIK 16 Digit",
    },
    {
      id: "nama",
      label: "NAMA",
      type: "text",
      placeholder: "john_doe",
    },
    {
      id: "keterangan",
      label: "Keterangan",
      type: "select",
      placeholder: "Keterangan",
      options: [
        { value: "option1", label: "PEMULA" },
        { value: "option2", label: "KEHILANGAN" },
        { value: "option3", label: "CETAK ULANG(CU)" },
        { value: "option4", label: "KADOMBAKITA" },
        { value: "option5", label: "ONLINE SKD" },
        { value: "option6", label: "ONLINE AKM" },
        { value: "option7", label: "ONLINE BIODATA" },
        { value: "option8", label: "PERUBAHAN DATA" },
        { value: "option9", label: "BANTUAN PINDAH" },
        { value: "option10", label: "GANTI FOTO" },
        { value: "option11", label: "GANTI TTD" },
        { value: "option12", label: "GANTI FOTO + TTD" },
        { value: "option13", label: "SKD + GANTI FOTO" },
        { value: "option14", label: "LD" },
        { value: "option15", label: "RUSAK" },
      ],
    },
    {
      id: "tanggal",
      label: "TANGGAL",
      type: "date",
      placeholder: "dd/mm/yyyy",
    },
  ];

  export const tengahInputs = [
    {
      id: "nik",
      label: "NIK",
      type: "text",
      placeholder: "NIK 16 Digit",
    },
    {
      id: "nama",
      label: "NAMA",
      type: "text",
      placeholder: "john_doe",
    },
    {
      id: "keterangan",
      label: "Keterangan",
      type: "select",
      placeholder: "Keterangan",
      options: [
        { value: "option1", label: "PEMULA" },
        { value: "option2", label: "KEHILANGAN" },
        { value: "option3", label: "CETAK ULANG(CU)" },
        { value: "option4", label: "KADOMBAKITA" },
        { value: "option5", label: "ONLINE SKD" },
        { value: "option6", label: "ONLINE AKM" },
        { value: "option7", label: "ONLINE BIODATA" },
        { value: "option8", label: "PERUBAHAN DATA" },
        { value: "option9", label: "BANTUAN PINDAH" },
        { value: "option10", label: "GANTI FOTO" },
        { value: "option11", label: "GANTI TTD" },
        { value: "option12", label: "GANTI FOTO + TTD" },
        { value: "option13", label: "SKD + GANTI FOTO" },
        { value: "option14", label: "LD" },
        { value: "option15", label: "RUSAK" },
      ],
    },
    {
      id: "tanggal",
      label: "TANGGAL",
      type: "date",
      placeholder: "dd/mm/yyyy",
    },
  ];

  export const baratInputs = [
    {
      id: "nik",
      label: "NIK",
      type: "text",
      placeholder: "NIK 16 Digit",
    },
    {
      id: "nama",
      label: "NAMA",
      type: "text",
      placeholder: "john_doe",
    },
    {
      id: "keterangan",
      label: "Keterangan",
      type: "select",
      placeholder: "Keterangan",
      options: [
        { value: "option1", label: "PEMULA" },
        { value: "option2", label: "KEHILANGAN" },
        { value: "option3", label: "CETAK ULANG(CU)" },
        { value: "option4", label: "KADOMBAKITA" },
        { value: "option5", label: "ONLINE SKD" },
        { value: "option6", label: "ONLINE AKM" },
        { value: "option7", label: "ONLINE BIODATA" },
        { value: "option8", label: "PERUBAHAN DATA" },
        { value: "option9", label: "BANTUAN PINDAH" },
        { value: "option10", label: "GANTI FOTO" },
        { value: "option11", label: "GANTI TTD" },
        { value: "option12", label: "GANTI FOTO + TTD" },
        { value: "option13", label: "SKD + GANTI FOTO" },
        { value: "option14", label: "LD" },
        { value: "option15", label: "RUSAK" },
      ],
    },
    {
      id: "tanggal",
      label: "TANGGAL",
      type: "date",
      placeholder: "dd/mm/yyyy",
    },
  ];
  
  export const timurInputs = [
    {
      id: "nik",
      label: "NIK",
      type: "text",
      placeholder: "NIK 16 Digit",
    },
    {
      id: "nama",
      label: "NAMA",
      type: "text",
      placeholder: "john_doe",
    },
    {
      id: "keterangan",
      label: "Keterangan",
      type: "select",
      placeholder: "Keterangan",
      options: [
        { value: "option1", label: "PEMULA" },
        { value: "option2", label: "KEHILANGAN" },
        { value: "option3", label: "CETAK ULANG(CU)" },
        { value: "option4", label: "KADOMBAKITA" },
        { value: "option5", label: "ONLINE SKD" },
        { value: "option6", label: "ONLINE AKM" },
        { value: "option7", label: "ONLINE BIODATA" },
        { value: "option8", label: "PERUBAHAN DATA" },
        { value: "option9", label: "BANTUAN PINDAH" },
        { value: "option10", label: "GANTI FOTO" },
        { value: "option11", label: "GANTI TTD" },
        { value: "option12", label: "GANTI FOTO + TTD" },
        { value: "option13", label: "SKD + GANTI FOTO" },
        { value: "option14", label: "LD" },
        { value: "option15", label: "RUSAK" },
      ],
    },
    {
      id: "tanggal",
      label: "TANGGAL",
      type: "date",
      placeholder: "dd/mm/yyyy",
    },
  ];

  export const utaraInputs = [
    {
      id: "nik",
      label: "NIK",
      type: "text",
      placeholder: "NIK 16 Digit",
    },
    {
      id: "nama",
      label: "NAMA",
      type: "text",
      placeholder: "john_doe",
    },
    {
      id: "keterangan",
      label: "Keterangan",
      type: "select",
      placeholder: "Keterangan",
      options: [
        { value: "option1", label: "PEMULA" },
        { value: "option2", label: "KEHILANGAN" },
        { value: "option3", label: "CETAK ULANG(CU)" },
        { value: "option4", label: "KADOMBAKITA" },
        { value: "option5", label: "ONLINE SKD" },
        { value: "option6", label: "ONLINE AKM" },
        { value: "option7", label: "ONLINE BIODATA" },
        { value: "option8", label: "PERUBAHAN DATA" },
        { value: "option9", label: "BANTUAN PINDAH" },
        { value: "option10", label: "GANTI FOTO" },
        { value: "option11", label: "GANTI TTD" },
        { value: "option12", label: "GANTI FOTO + TTD" },
        { value: "option13", label: "SKD + GANTI FOTO" },
        { value: "option14", label: "LD" },
        { value: "option15", label: "RUSAK" },
      ],
    },
    {
      id: "tanggal",
      label: "TANGGAL",
      type: "date",
      placeholder: "dd/mm/yyyy",
    },
  ];

  export const selatanInputs = [
    {
      id: "nik",
      label: "NIK",
      type: "text",
      placeholder: "NIK 16 Digit",
    },
    {
      id: "nama",
      label: "NAMA",
      type: "text",
      placeholder: "john_doe",
    },
    {
      id: "keterangan",
      label: "Keterangan",
      type: "select",
      placeholder: "Keterangan",
      options: [
        { value: "option1", label: "PEMULA" },
        { value: "option2", label: "KEHILANGAN" },
        { value: "option3", label: "CETAK ULANG(CU)" },
        { value: "option4", label: "KADOMBAKITA" },
        { value: "option5", label: "ONLINE SKD" },
        { value: "option6", label: "ONLINE AKM" },
        { value: "option7", label: "ONLINE BIODATA" },
        { value: "option8", label: "PERUBAHAN DATA" },
        { value: "option9", label: "BANTUAN PINDAH" },
        { value: "option10", label: "GANTI FOTO" },
        { value: "option11", label: "GANTI TTD" },
        { value: "option12", label: "GANTI FOTO + TTD" },
        { value: "option13", label: "SKD + GANTI FOTO" },
        { value: "option14", label: "LD" },
        { value: "option15", label: "RUSAK" },
      ],
    },
    {
      id: "tanggal",
      label: "TANGGAL",
      type: "date",
      placeholder: "dd/mm/yyyy",
    },
  ];
  
  export const banyumanikInputs = [
    {
      id: "nik",
      label: "NIK",
      type: "text",
      placeholder: "NIK 16 Digit",
    },
    {
      id: "nama",
      label: "NAMA",
      type: "text",
      placeholder: "john_doe",
    },
    {
      id: "keterangan",
      label: "Keterangan",
      type: "select",
      placeholder: "Keterangan",
      options: [
        { value: "option1", label: "PEMULA" },
        { value: "option2", label: "KEHILANGAN" },
        { value: "option3", label: "CETAK ULANG(CU)" },
        { value: "option4", label: "KADOMBAKITA" },
        { value: "option5", label: "ONLINE SKD" },
        { value: "option6", label: "ONLINE AKM" },
        { value: "option7", label: "ONLINE BIODATA" },
        { value: "option8", label: "PERUBAHAN DATA" },
        { value: "option9", label: "BANTUAN PINDAH" },
        { value: "option10", label: "GANTI FOTO" },
        { value: "option11", label: "GANTI TTD" },
        { value: "option12", label: "GANTI FOTO + TTD" },
        { value: "option13", label: "SKD + GANTI FOTO" },
        { value: "option14", label: "LD" },
        { value: "option15", label: "RUSAK" },
      ],
    },
    {
      id: "tanggal",
      label: "TANGGAL",
      type: "date",
      placeholder: "dd/mm/yyyy",
    },
  ];

  export const candisariInputs = [
    {
      id: "nik",
      label: "NIK",
      type: "text",
      placeholder: "NIK 16 Digit",
    },
    {
      id: "nama",
      label: "NAMA",
      type: "text",
      placeholder: "john_doe",
    },
    {
      id: "keterangan",
      label: "Keterangan",
      type: "select",
      placeholder: "Keterangan",
      options: [
        { value: "option1", label: "PEMULA" },
        { value: "option2", label: "KEHILANGAN" },
        { value: "option3", label: "CETAK ULANG(CU)" },
        { value: "option4", label: "KADOMBAKITA" },
        { value: "option5", label: "ONLINE SKD" },
        { value: "option6", label: "ONLINE AKM" },
        { value: "option7", label: "ONLINE BIODATA" },
        { value: "option8", label: "PERUBAHAN DATA" },
        { value: "option9", label: "BANTUAN PINDAH" },
        { value: "option10", label: "GANTI FOTO" },
        { value: "option11", label: "GANTI TTD" },
        { value: "option12", label: "GANTI FOTO + TTD" },
        { value: "option13", label: "SKD + GANTI FOTO" },
        { value: "option14", label: "LD" },
        { value: "option15", label: "RUSAK" },
      ],
    },
    {
      id: "tanggal",
      label: "TANGGAL",
      type: "date",
      placeholder: "dd/mm/yyyy",
    },
  ];

  export const gajahmungkurInputs = [
    {
      id: "nik",
      label: "NIK",
      type: "text",
      placeholder: "NIK 16 Digit",
    },
    {
      id: "nama",
      label: "NAMA",
      type: "text",
      placeholder: "john_doe",
    },
    {
      id: "keterangan",
      label: "Keterangan",
      type: "select",
      placeholder: "Keterangan",
      options: [
        { value: "option1", label: "PEMULA" },
        { value: "option2", label: "KEHILANGAN" },
        { value: "option3", label: "CETAK ULANG(CU)" },
        { value: "option4", label: "KADOMBAKITA" },
        { value: "option5", label: "ONLINE SKD" },
        { value: "option6", label: "ONLINE AKM" },
        { value: "option7", label: "ONLINE BIODATA" },
        { value: "option8", label: "PERUBAHAN DATA" },
        { value: "option9", label: "BANTUAN PINDAH" },
        { value: "option10", label: "GANTI FOTO" },
        { value: "option11", label: "GANTI TTD" },
        { value: "option12", label: "GANTI FOTO + TTD" },
        { value: "option13", label: "SKD + GANTI FOTO" },
        { value: "option14", label: "LD" },
        { value: "option15", label: "RUSAK" },
      ],
    },
    {
      id: "tanggal",
      label: "TANGGAL",
      type: "date",
      placeholder: "dd/mm/yyyy",
    },
  ];
  
  export const genukInputs = [
    {
      id: "nik",
      label: "NIK",
      type: "text",
      placeholder: "NIK 16 Digit",
    },
    {
      id: "nama",
      label: "NAMA",
      type: "text",
      placeholder: "john_doe",
    },
    {
      id: "keterangan",
      label: "Keterangan",
      type: "select",
      placeholder: "Keterangan",
      options: [
        { value: "option1", label: "PEMULA" },
        { value: "option2", label: "KEHILANGAN" },
        { value: "option3", label: "CETAK ULANG(CU)" },
        { value: "option4", label: "KADOMBAKITA" },
        { value: "option5", label: "ONLINE SKD" },
        { value: "option6", label: "ONLINE AKM" },
        { value: "option7", label: "ONLINE BIODATA" },
        { value: "option8", label: "PERUBAHAN DATA" },
        { value: "option9", label: "BANTUAN PINDAH" },
        { value: "option10", label: "GANTI FOTO" },
        { value: "option11", label: "GANTI TTD" },
        { value: "option12", label: "GANTI FOTO + TTD" },
        { value: "option13", label: "SKD + GANTI FOTO" },
        { value: "option14", label: "LD" },
        { value: "option15", label: "RUSAK" },
      ],
    },
    {
      id: "tanggal",
      label: "TANGGAL",
      type: "date",
      placeholder: "dd/mm/yyyy",
    },
  ];

  export const gunungpatiInputs = [
    {
      id: "nik",
      label: "NIK",
      type: "text",
      placeholder: "NIK 16 Digit",
    },
    {
      id: "nama",
      label: "NAMA",
      type: "text",
      placeholder: "john_doe",
    },
    {
      id: "keterangan",
      label: "Keterangan",
      type: "select",
      placeholder: "Keterangan",
      options: [
        { value: "option1", label: "PEMULA" },
        { value: "option2", label: "KEHILANGAN" },
        { value: "option3", label: "CETAK ULANG(CU)" },
        { value: "option4", label: "KADOMBAKITA" },
        { value: "option5", label: "ONLINE SKD" },
        { value: "option6", label: "ONLINE AKM" },
        { value: "option7", label: "ONLINE BIODATA" },
        { value: "option8", label: "PERUBAHAN DATA" },
        { value: "option9", label: "BANTUAN PINDAH" },
        { value: "option10", label: "GANTI FOTO" },
        { value: "option11", label: "GANTI TTD" },
        { value: "option12", label: "GANTI FOTO + TTD" },
        { value: "option13", label: "SKD + GANTI FOTO" },
        { value: "option14", label: "LD" },
        { value: "option15", label: "RUSAK" },
      ],
    },
    {
      id: "tanggal",
      label: "TANGGAL",
      type: "date",
      placeholder: "dd/mm/yyyy",
    },
  ];
  
  export const mijenInputs = [
    {
      id: "nik",
      label: "NIK",
      type: "text",
      placeholder: "NIK 16 Digit",
    },
    {
      id: "nama",
      label: "NAMA",
      type: "text",
      placeholder: "john_doe",
    },
    {
      id: "keterangan",
      label: "Keterangan",
      type: "select",
      placeholder: "Keterangan",
      options: [
        { value: "option1", label: "PEMULA" },
        { value: "option2", label: "KEHILANGAN" },
        { value: "option3", label: "CETAK ULANG(CU)" },
        { value: "option4", label: "KADOMBAKITA" },
        { value: "option5", label: "ONLINE SKD" },
        { value: "option6", label: "ONLINE AKM" },
        { value: "option7", label: "ONLINE BIODATA" },
        { value: "option8", label: "PERUBAHAN DATA" },
        { value: "option9", label: "BANTUAN PINDAH" },
        { value: "option10", label: "GANTI FOTO" },
        { value: "option11", label: "GANTI TTD" },
        { value: "option12", label: "GANTI FOTO + TTD" },
        { value: "option13", label: "SKD + GANTI FOTO" },
        { value: "option14", label: "LD" },
        { value: "option15", label: "RUSAK" },
      ],
    },
    {
      id: "tanggal",
      label: "TANGGAL",
      type: "date",
      placeholder: "dd/mm/yyyy",
    },
  ];

  export const ngaliyanInputs = [
    {
      id: "nik",
      label: "NIK",
      type: "text",
      placeholder: "NIK 16 Digit",
    },
    {
      id: "nama",
      label: "NAMA",
      type: "text",
      placeholder: "john_doe",
    },
    {
      id: "keterangan",
      label: "Keterangan",
      type: "select",
      placeholder: "Keterangan",
      options: [
        { value: "option1", label: "PEMULA" },
        { value: "option2", label: "KEHILANGAN" },
        { value: "option3", label: "CETAK ULANG(CU)" },
        { value: "option4", label: "KADOMBAKITA" },
        { value: "option5", label: "ONLINE SKD" },
        { value: "option6", label: "ONLINE AKM" },
        { value: "option7", label: "ONLINE BIODATA" },
        { value: "option8", label: "PERUBAHAN DATA" },
        { value: "option9", label: "BANTUAN PINDAH" },
        { value: "option10", label: "GANTI FOTO" },
        { value: "option11", label: "GANTI TTD" },
        { value: "option12", label: "GANTI FOTO + TTD" },
        { value: "option13", label: "SKD + GANTI FOTO" },
        { value: "option14", label: "LD" },
        { value: "option15", label: "RUSAK" },
      ],
    },
    {
      id: "tanggal",
      label: "TANGGAL",
      type: "date",
      placeholder: "dd/mm/yyyy",
    },
  ];

  export const pedurunganInputs = [
    {
      id: "nik",
      label: "NIK",
      type: "text",
      placeholder: "NIK 16 Digit",
    },
    {
      id: "nama",
      label: "NAMA",
      type: "text",
      placeholder: "john_doe",
    },
    {
      id: "keterangan",
      label: "Keterangan",
      type: "select",
      placeholder: "Keterangan",
      options: [
        { value: "option1", label: "PEMULA" },
        { value: "option2", label: "KEHILANGAN" },
        { value: "option3", label: "CETAK ULANG(CU)" },
        { value: "option4", label: "KADOMBAKITA" },
        { value: "option5", label: "ONLINE SKD" },
        { value: "option6", label: "ONLINE AKM" },
        { value: "option7", label: "ONLINE BIODATA" },
        { value: "option8", label: "PERUBAHAN DATA" },
        { value: "option9", label: "BANTUAN PINDAH" },
        { value: "option10", label: "GANTI FOTO" },
        { value: "option11", label: "GANTI TTD" },
        { value: "option12", label: "GANTI FOTO + TTD" },
        { value: "option13", label: "SKD + GANTI FOTO" },
        { value: "option14", label: "LD" },
        { value: "option15", label: "RUSAK" },
      ],
    },
    {
      id: "tanggal",
      label: "TANGGAL",
      type: "date",
      placeholder: "dd/mm/yyyy",
    },
  ];

  export const tembalangInputs = [
    {
      id: "nik",
      label: "NIK",
      type: "text",
      placeholder: "NIK 16 Digit",
    },
    {
      id: "nama",
      label: "NAMA",
      type: "text",
      placeholder: "john_doe",
    },
    {
      id: "keterangan",
      label: "Keterangan",
      type: "select",
      placeholder: "Keterangan",
      options: [
        { value: "option1", label: "PEMULA" },
        { value: "option2", label: "KEHILANGAN" },
        { value: "option3", label: "CETAK ULANG(CU)" },
        { value: "option4", label: "KADOMBAKITA" },
        { value: "option5", label: "ONLINE SKD" },
        { value: "option6", label: "ONLINE AKM" },
        { value: "option7", label: "ONLINE BIODATA" },
        { value: "option8", label: "PERUBAHAN DATA" },
        { value: "option9", label: "BANTUAN PINDAH" },
        { value: "option10", label: "GANTI FOTO" },
        { value: "option11", label: "GANTI TTD" },
        { value: "option12", label: "GANTI FOTO + TTD" },
        { value: "option13", label: "SKD + GANTI FOTO" },
        { value: "option14", label: "LD" },
        { value: "option15", label: "RUSAK" },
      ],
    },
    {
      id: "tanggal",
      label: "TANGGAL",
      type: "date",
      placeholder: "dd/mm/yyyy",
    },
  ];

  export const tuguInputs = [
    {
      id: "nik",
      label: "NIK",
      type: "text",
      placeholder: "NIK 16 Digit",
    },
    {
      id: "nama",
      label: "NAMA",
      type: "text",
      placeholder: "john_doe",
    },
    {
      id: "keterangan",
      label: "Keterangan",
      type: "select",
      placeholder: "Keterangan",
      options: [
        { value: "option1", label: "PEMULA" },
        { value: "option2", label: "KEHILANGAN" },
        { value: "option3", label: "CETAK ULANG(CU)" },
        { value: "option4", label: "KADOMBAKITA" },
        { value: "option5", label: "ONLINE SKD" },
        { value: "option6", label: "ONLINE AKM" },
        { value: "option7", label: "ONLINE BIODATA" },
        { value: "option8", label: "PERUBAHAN DATA" },
        { value: "option9", label: "BANTUAN PINDAH" },
        { value: "option10", label: "GANTI FOTO" },
        { value: "option11", label: "GANTI TTD" },
        { value: "option12", label: "GANTI FOTO + TTD" },
        { value: "option13", label: "SKD + GANTI FOTO" },
        { value: "option14", label: "LD" },
        { value: "option15", label: "RUSAK" },
      ],
    },
    {
      id: "tanggal",
      label: "TANGGAL",
      type: "date",
      placeholder: "dd/mm/yyyy",
    },
  ];

  export const productInputs = [
    {
      id: 1,
      label: "Title",
      type: "text",
      placeholder: "Apple Macbook Pro",
    },
    {
      id: 2,
      label: "Description",
      type: "text",
      placeholder: "Description",
    },
    {
      id: 3,
      label: "Category",
      type: "text",
      placeholder: "Computers",
    },
    {
      id: 4,
      label: "Price",
      type: "text",
      placeholder: "100",
    },
    {
      id: 5,
      label: "Stock",
      type: "text",
      placeholder: "in stock",
    },
  ];